# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 373)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLable = QtWidgets.QLabel(self.centralwidget)
        self.titleLable.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.titleLable.setFont(font)
        self.titleLable.setObjectName("titleLable")
        self.englishBox = QtWidgets.QTextEdit(self.centralwidget)
        self.englishBox.setGeometry(QtCore.QRect(30, 110, 311, 151))
        self.englishBox.setObjectName("englishBox")
        self.spanishBox = QtWidgets.QTextEdit(self.centralwidget)
        self.spanishBox.setGeometry(QtCore.QRect(430, 110, 311, 151))
        self.spanishBox.setObjectName("spanishBox")
        self.translateButton = QtWidgets.QPushButton(self.centralwidget)
        self.translateButton.setGeometry(QtCore.QRect(30, 290, 75, 23))
        self.translateButton.setObjectName("translateButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EnglishSpanishNMT"))
        self.titleLable.setText(_translate("MainWindow", "English to Spanish Translator"))
        self.englishBox.setPlaceholderText(_translate("MainWindow", "Input English Here"))
        self.spanishBox.setPlaceholderText(_translate("MainWindow", "Translation Output Here"))
        self.translateButton.setText(_translate("MainWindow", "Translate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
